export const data = [
  {
    "id": "1", 
    "name": "To Kill a Mockingbird",
    "author": "Harper Lee",
    "description": "A powerful novel set in the racially segregated American South, where young Scout Finch witnesses her father, a principled lawyer, defending an innocent black man in a deeply prejudiced society. The book explores themes of morality, justice, and empathy.",
    "pdfUrl": "https://drive.google.com/uc?id=1Exe1DnJDlyJgpNsLLAL-qJEgV84TIyxb&export=download",
    "price": "124",
    "genre": "Fiction",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/To%20Kill%20a%20Mockingbird.jpg",
    "publishDate": "1960-07-11",
    "uploadDate": "2025-02-13T17:59:54.241Z",
    "downloadCount": 0,
    "visitCount": 0,
    "ratings": [5, 4, 4, 5]
  },
  {
    "id": "2",
    "name": "1984",
    "author": "George Orwell",
    "description": "A haunting vision of a dystopian future where a totalitarian regime, led by Big Brother, suppresses individual freedom and manipulates truth. This novel warns against the dangers of unchecked government power and surveillance.",
    "pdfUrl": "https://drive.google.com/uc?id=1V-rAoqAGUWJv_3UvbAs9I4jA-QTAL1wC&export=download",
    "price": "100",
    "genre": "Dystopian",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/1984.jpg",
    "publishDate": "1949-06-08",
    "uploadDate": "2025-02-13T18:06:47.132Z",
    "downloadCount": 0,
    "visitCount": 0,
    "ratings": [3, 5, 4]
  },
  {
    "id": "3",
    "name": "The Great Gatsby",
    "author": "F. Scott Fitzgerald",
    "description": "A tragic tale of love, wealth, and the American Dream, following the mysterious millionaire Jay Gatsby and his obsession with the unattainable Daisy Buchanan. Set in the Roaring Twenties, the novel exposes the emptiness of high society.",
    "pdfUrl": "https://drive.google.com/uc?id=1gVicxGhmr6skKCK_T5mdQTcsbZsVuFeG&export=download",
    "price": "90",
    "genre": "Fiction",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/The%20Great%20Gatsby.jpg",
    "publishDate": "1925-04-10",
    "uploadDate": "2025-02-13T18:09:44.415Z",
    "downloadCount": 0,
    "visitCount": 0,
    "ratings": [4, 4, 5, 3, 4]
  },
  {
    "id": "4", 
    "name": "The Catcher in the Rye",
    "author": "J.D. Salinger",
    "description": "An introspective novel about teenage alienation, following Holden Caulfield, a rebellious youth who struggles with the hypocrisy of the adult world. His journey through New York City reflects his search for meaning and authenticity.",
    "pdfUrl": "https://drive.google.com/uc?id=1yDbV-JBF3jtVW5TBojD-jDErXgYA7kKt&export=download",
    "price": "70",
    "genre": "Fiction",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/The%20Catcher%20in%20the%20Rye.jpg",
    "publishDate": "1951-07-16",
    "uploadDate": "2025-02-13T18:11:19.307Z",
    "downloadCount": 0,
    "visitCount": 0,
    "ratings": [5, 3, 4]
  },
  {
    "id": "5",
    "name": "Pride and Prejudice",
    "author": "Jane Austen",
    "description": "A beloved classic that explores the themes of love, social class, and personal growth through the witty and independent Elizabeth Bennet as she navigates her evolving relationship with the proud but honorable Mr. Darcy.",
    "pdfUrl": "https://drive.google.com/uc?id=1abcXYZ&export=download",
    "price": "85",
    "genre": "Romance",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/Pride%20and%20Prejudice.jpg",
    "publishDate": "1813-01-28",
    "uploadDate": "2025-02-13T18:14:00.512Z",
    "downloadCount": 0,
    "visitCount": 0,
    "ratings": [4, 5, 5, 4]
  },
  {
    "id": "6",
    "name": "The Hobbit",
    "author": "J.R.R. Tolkien",
    "description": "The Hobbit, or There and Back Again is a children's fantasy novel by English author J. R. R. Tolkien. It was published in 1937 to wide critical acclaim, being nominated for the Carnegie Medal and awarded a prize from the New York Herald Tribune for best juvenile fiction.",
    "pdfUrl": "https://drive.google.com/uc?id=1def456&export=download",
    "price": "200",
    "genre": "Fantasy",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/The%20Hobbit.jpg",
    "publishDate": "1954-07-29",
    "uploadDate": "2025-02-13T18:16:30.741Z",
    "downloadCount": 0,
    "visitCount": 0,
    "ratings": [5, 5, 4, 4]
  },
  {
    "id": "7",
    "name": "Moby-Dick",
    "author": "Herman Melville",
    "description": "A deep and symbolic novel that follows Captain Ahab’s obsessive quest to hunt down the elusive white whale, Moby-Dick. The book explores themes of revenge, fate, and the human struggle against nature.",
    "pdfUrl": "https://drive.google.com/uc?id=1ghi789&export=download",
    "price": "110",
    "genre": "Adventure",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/Moby-Dick.jpg",
    "publishDate": "1851-10-18",
    "uploadDate": "2025-02-13T18:19:40.293Z",
    "downloadCount": 0,
    "visitCount": 0,
    "ratings": [3, 4, 4, 5]
  },
  {
    "id": "8",
    "name": "Crime and Punishment",
    "author": "Fyodor Dostoevsky",
    "description": "A psychological novel exploring guilt and redemption, following Raskolnikov, a poor student who commits a crime to test his moral theory but struggles with the overwhelming guilt that follows.",
    "pdfUrl": "https://drive.google.com/uc?id=1jkl012&export=download",
    "price": "95",
    "genre": "Psychological Fiction",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/Crime%20and%20Punishment.jpg",
    "publishDate": "1866-01-01",
    "uploadDate": "2025-02-13T18:21:14.627Z",
    "downloadCount": 0,
    "visitCount": 0,
    "ratings": [4, 5, 3]
  },
  {
    "id": "9",
    "name": "Brave New World",
    "author": "Aldous Huxley",
    "description": "A dystopian novel set in a futuristic world where technological advancements have led to a society of engineered happiness and control, questioning the cost of true freedom.",
    "pdfUrl": "https://drive.google.com/uc?id=1mno345&export=download",
    "price": "88",
    "genre": "Dystopian",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/Brave%20New%20World.jpg",
    "publishDate": "1932-01-01",
    "uploadDate": "2025-02-13T18:23:41.218Z",
    "downloadCount": 0,
    "visitCount": 0,
    "ratings": [5, 4, 4, 3]
  },
  {
    "id": "10",
    "name": "The Brothers Karamazov",
    "author": "Fyodor Dostoevsky",
    "description": "A philosophical and psychological novel exploring faith, free will, and morality through the complex relationships of three brothers and their conflicting beliefs.",
    "pdfUrl": "https://drive.google.com/uc?id=1pqr678&export=download",
    "price": "130",
    "genre": "Philosophical Fiction",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/The%20Brothers%20Karamazov.jpg",
    "publishDate": "1880-01-01",
    "uploadDate": "2025-02-13T18:26:07.342Z",
    "downloadCount": 0,
    "visitCount": 0,
    "ratings": [4, 5, 5, 4]
  },
  {
    "id": "11",
    "name": "Frankenstein",
    "author": "Mary Shelley",
    "description": "A Gothic horror novel about a scientist, Victor Frankenstein, who creates a living being but is horrified by his own creation, leading to tragic consequences.",
    "pdfUrl": "https://drive.google.com/uc?id=1stu901&export=download",
    "price": "75",
    "genre": "Horror",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/Frankenstein.jpg",
    "publishDate": "1818-01-01",
    "uploadDate": "2025-02-13T18:27:59.134Z",
    "downloadCount": 0,
    "visitCount": 0,
    "ratings": [3, 4, 4, 5]
  },
  {
    "id": "12",
    "name": "Dracula",
    "author": "Bram Stoker",
    "description": "A classic vampire novel that introduced Count Dracula and set the foundation for modern vampire lore, blending horror, romance, and suspense.",
    "pdfUrl": "https://drive.google.com/uc?id=1uvw234&export=download",
    "price": "85",
    "genre": "Horror",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/Dracula.jpg",
    "publishDate": "1897-05-26",
    "uploadDate": "2025-02-13T18:30:11.564Z",
    "downloadCount": 0,
    "visitCount": 0,
    "ratings": [4, 5, 4]
  },
  {
    "id": "13",
    "name": "Jane Eyre",
    "author": "Charlotte Brontë",
    "description": "A coming-of-age novel following Jane Eyre, an independent and intelligent orphan, as she overcomes hardship and finds love, while challenging social norms.",
    "pdfUrl": "https://drive.google.com/uc?id=1xyz567&export=download",
    "price": "95",
    "genre": "Romance",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/Jane%20Eyre.jpg",
    "publishDate": "1847-10-16",
    "uploadDate": "2025-02-13T18:33:48.832Z",
    "downloadCount": 0,
    "visitCount": 0,
    "ratings": [5, 4, 4, 3]
  },
  {
    "id": "14",
    "name": "Wuthering Heights",
    "author": "Emily Brontë",
    "description": "A tragic and intense novel about love and revenge, following the doomed romance between Heathcliff and Catherine in the Yorkshire moors.",
    "pdfUrl": "https://drive.google.com/uc?id=1abc890&export=download",
    "price": "90",
    "genre": "Romance",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/Wuthering%20Heights.jpg",
    "publishDate": "1847-12-17",
    "uploadDate": "2025-02-13T18:35:29.214Z",
    "downloadCount": 0,
    "visitCount": 0,
    "ratings": [4, 5, 3]
  },
  {
    "id": "15",
    "name": "The Picture of Dorian Gray",
    "author": "Oscar Wilde",
    "description": "A philosophical novel exploring vanity and morality, where Dorian Gray remains young while his portrait ages, reflecting his corrupt soul.",
    "pdfUrl": "https://drive.google.com/uc?id=1def123&export=download",
    "price": "80",
    "genre": "Philosophical Fiction",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/The%20Picture%20of%20Dorian%20Gray.jpg",
    "publishDate": "1890-06-20",
    "uploadDate": "2025-02-13T18:37:14.892Z",
    "downloadCount": 0,
    "visitCount": 0,
    "ratings": [5, 4, 4, 5]
  },
  {
    "id": "16",
    "name": "The Iliad",
    "author": "Homer",
    "description": "The Iliad is one of two major ancient Greek epic poems attributed to Homer. It is one of the oldest extant works of literature still widely read by modern audiences.",
    "pdfUrl": "https://drive.google.com/uc?id=1ghi456&export=download",
    "price": "140",
    "genre": "Historical Fiction",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/Library-images/main/The%20Iliad.jpg",
    "publishDate": "1862-01-01",
    "uploadDate": "2025-02-13T18:39:23.763Z",
    "downloadCount": 0,
    "visitCount": 0,
    "ratings": [4, 5, 3, 4]
  },
  {
    "id": "17",
    "name": "War and Peace",
    "author": "Leo Tolstoy",
    "description": "An epic novel that intertwines history, philosophy, and personal drama, portraying Russian aristocracy during the Napoleonic Wars.",
    "pdfUrl": "https://drive.google.com/uc?id=1jkl789&export=download",
    "price": "150",
    "genre": "Historical Fiction",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/War%20and%20Peace.jpg",
    "publishDate": "1869-01-01",
    "uploadDate": "2025-02-13T18:42:05.372Z",
    "downloadCount": 0,
    "visitCount": 0,
    "ratings": [5, 4, 4, 5]
  },
  {
    "id": "18",
    "name": "Dracula",
    "author": "Bram Stoker",
    "description": "A novel about the vampire Count Dracula's attempt to move from Transylvania to England.",
    "pdfUrl": "https://drive.google.com/uc?id=1019dSDipxmQbG14kbBX1BoOME2rwJiWy&export=download",
    "price": "90",
    "genre": "Horror",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/Dracula.jpg",
    "publishDate": "1897-05-26",
    "uploadDate": "2025-02-13T18:31:21.092Z",
    "downloadCount": 0,
    "visitCount": 0,
    "ratings": [4, 5, 4]
  },
  {
    "id": "19",
    "name": "The Picture of Dorian Gray",
    "author": "Oscar Wilde",
    "description": "A novel about a man who remains young while his portrait ages.",
    "pdfUrl": "https://drive.google.com/uc?id=1wcsPRseCNZ2JEfHRxCrYH7hzjDRiIU2J&export=download",
    "price": "80",
    "genre": "Philosophical Fiction",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/The%20Picture%20of%20Dorian%20Gray.jpg",
    "publishDate": "1890-06-20",
    "uploadDate": "2025-02-13T18:32:27.292Z",
    "downloadCount": 0,
    "visitCount": 0,
    "ratings": [5, 4, 4, 5]
  },
  {
    "id": "20",
    "name": "Anna Karenina",
    "author": "Leo Tolstoy",
    "description": "A novel about the tragic love affair between Anna Karenina and Count Vronsky.",
    "pdfUrl": "https://drive.google.com/uc?id=1t0jFThYJVn--_83oqu8C65r5osjqNLZw&export=download",
    "price": "120",
    "genre": "Romance",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/Anna%20Karenina.jpg",
    "publishDate": "1877-01-01",
    "uploadDate": "2025-02-13T18:33:14.736Z",
    "downloadCount": "0",
    "visitCount": "0",
    "ratings": [4, 5, 3, 4]
  },
  {
    "id": "21",
    "name": "The Time Machine Book",
    "author": "H. G. Wells",
    "description": "The Time Machine is an 1895 dystopian post-apocalyptic science fiction novella by H. G. Wells about a Victorian scientist known as the Time Traveller who travels to the year 802,701",
    "pdfUrl": "https://drive.google.com/uc?id=1Vx4c5TZETS9kxW1G9_cddJMu6mlaFkSo&export=download",
    "price": "120",
    "genre": "Sci-Fi",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/The%20Time%20Machine%20Book.jpg",
    "publishDate": "7 May 1895",
    "uploadDate": "2025-02-13T18:34:42.925Z",
    "downloadCount": "0",
    "visitCount": "0",
    "ratings": [5, 4, 4, 5]
  },
  {
    "id": "22",
    "name": "The Lost World",
    "author": "Arthur Conan Doyle",
    "description": "The Lost World is a science fiction novel by British writer Sir Arthur Conan Doyle, published by Hodder & Stoughton in 1912, concerning an expedition to a plateau in the Amazon basin of South America where prehistoric animals still survive.",
    "pdfUrl": "https://drive.google.com/uc?id=1We79NT6Npn7S9CxruFQSI0fW79fZ4a4n&export=download",
    "price": "100",
    "genre": "Sci-Fi",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/The%20Lost%20World.jpg",
    "publishDate": "21 july 1912",
    "uploadDate": "2025-02-13T18:35:44.805Z",
    "downloadCount": "0",
    "visitCount": "0",
    "ratings": [4, 5, 3]
  },
  {
    "id": "23",
    "name": "The Art of Public Speaking",
    "author": "Dale Breckenridge Carnegie",
    "description": "Dale Breckenridge has written many books on self development including like \\\"How to Win Friends and Influence People\\\",\\\"How to Stop Worrying and Start Living\\\" and \\\"Lincoln the Unknown\\\" to name a few. \\\"The Art of Public Speaking\\\" is a book not for a seasoned public speaker. It can be an academic guide for aspiring public speakers.",
    "pdfUrl": "https://drive.google.com/uc?id=1700mFWAWdpral_Y1MBAYKMwTQqwi2dpR&export=download",
    "price": "90",
    "genre": "Self-help",
    "availability": true,
    "imageUrl": "https://raw.githubusercontent.com/Kshitij-Bagal/library-images/main/The%20Art%20of%20Public%20Speaking.jpg",
    "publishDate": "1925-04-10",
    "uploadDate": "2025-02-13T18:37:35.693Z",
    "downloadCount": "0",
    "visitCount": "0",
    "ratings": [5, 4, 4, 5]
  }  
]